version: '3.8'

volumes:
  mysql-data:
  # tomcat-webapps-dir:

services:
  app:
    container_name: javadev
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      # NOTE: MYSQL_DATABASE/USER/PASSWORD should match values in db container
      MYSQL_HOST: mysqldb
      MYSQL_DATABASE: app
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password

    volumes:
      - ../..:/workspaces:cached
      # - tomcat-webapps-dir:/usr/local/tomcat/webapps

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  # web:
  #   depends_on:
  #     - db
  #   image: tomcat
  #   volumes:
  #     - tomcat-webapps-dir:/usr/local/tomcat/webapps

  db:
    container_name: mysqldb
    image: mysql:8.3
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment: 
      # NOTE: MYSQL_DATABASE/USER/PASSWORD should match values in app container
      MYSQL_DATABASE: app
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password

    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MySQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  redis:
    image: redis
    restart: unless-stopped
